# db/seeds/ingredients.rb

puts "Carregant ingredients..."

allergies = [
  "Gluten",
  "Lactosa",
  "Ou",
  "Fruits secs",
  "Cacauets",
  "Soja",
  "Peix",
  "Marisc",
  "Sèsam"
]

allergies.each do |name|
  Allergy.find_or_create_by!(name: name)
end

ingredients = [
  { name: "Arròs bomba", optional_description: "Arròs rodó ideal per arrossos secs i caldosos." },
  { name: "Macarrons", optional_description: "Pasta curta de blat.", allergies: [ "Gluten" ] },
  { name: "Espaguetis", optional_description: "Pasta llarga de blat.", allergies: [ "Gluten" ] },
  { name: "Farina de blat", optional_description: "Farina comuna per masses i salses.", allergies: [ "Gluten" ] },
  { name: "Pa ratllat", optional_description: "Per arrebossats i gratinats.", allergies: [ "Gluten" ] },
  { name: "Patata", optional_description: "Tubercle bàsic per guisats, cremes i guarnicions." },
  { name: "Ceba", optional_description: "Base aromàtica per sofregits." },
  { name: "All", optional_description: "Aromàtic essencial de cuina mediterrània." },
  { name: "Tomàquet madur", optional_description: "Per sofregits, amanides i salses." },
  { name: "Tomàquet triturat", optional_description: "Conserva de tomàquet per salses i guisats." },
  { name: "Pebrot vermell", optional_description: "Hortalissa dolça per sofregits i escalivades." },
  { name: "Pebrot verd", optional_description: "Hortalissa fresca per sofregits." },
  { name: "Pastanaga", optional_description: "Aporta dolçor a brous, cremes i guisats." },
  { name: "Carbassó", optional_description: "Verdura suau per cremes, planxa i saltejats." },
  { name: "Albergínia", optional_description: "Ideal per escalivades, forn i guisats." },
  { name: "Porro", optional_description: "Base dolça per cremes i brous." },
  { name: "Api", optional_description: "Aromàtic per brous i sofregits." },
  { name: "Enciam", optional_description: "Fulla fresca per amanides." },
  { name: "Ruca", optional_description: "Fulla amarga i aromàtica." },
  { name: "Cigrons cuits", optional_description: "Llegum cuit per amanides, guisats i hummus." },
  { name: "Llenties cuites", optional_description: "Llegum cuit per plats ràpids i amanides." },
  { name: "Mongetes seques cuites", optional_description: "Llegum cuit per guisats i amanides." },
  { name: "Pèsols", optional_description: "Llegum tendre per arrossos i guarnicions." },
  { name: "Pollastre", optional_description: "Carn blanca versàtil." },
  { name: "Vedella picada", optional_description: "Per bolonyesa, mandonguilles i farcits." },
  { name: "Bacallà dessalat", optional_description: "Peix blanc salat i dessalat.", allergies: [ "Peix" ] },
  { name: "Lluç", optional_description: "Peix blanc suau.", allergies: [ "Peix" ] },
  { name: "Gambes", optional_description: "Crustaci per arrossos i saltejats.", allergies: [ "Marisc" ] },
  { name: "Tonyina en conserva", optional_description: "Conserva de peix per amanides i pasta.", allergies: [ "Peix" ] },
  { name: "Ous", optional_description: "Ingredient bàsic per truites, postres i arrebossats.", allergies: [ "Ou" ] },
  { name: "Llet", optional_description: "Làctic per salses i postres.", allergies: [ "Lactosa" ] },
  { name: "Mantega", optional_description: "Greix làctic per salses i masses.", allergies: [ "Lactosa" ] },
  { name: "Formatge ratllat", optional_description: "Per gratinar pasta i verdures.", allergies: [ "Lactosa" ] },
  { name: "Iogurt natural", optional_description: "Làctic fresc per salses i postres.", allergies: [ "Lactosa" ] },
  { name: "Nata líquida", optional_description: "Crema de llet per salses.", allergies: [ "Lactosa" ] },
  { name: "Oli d'oliva verge extra", optional_description: "Greix principal de cuina mediterrània." },
  { name: "Vinagre de vi", optional_description: "Àcid per amanides i escabetxos." },
  { name: "Sal", optional_description: "Condiment bàsic." },
  { name: "Pebre negre", optional_description: "Espècia bàsica." },
  { name: "Pebre vermell dolç", optional_description: "Espècia dolça per guisats i llegums." },
  { name: "Comí", optional_description: "Espècia càlida per llegums i cremes." },
  { name: "Cúrcuma", optional_description: "Espècia de color groc intens." },
  { name: "Orenga", optional_description: "Herba seca per pasta i salses." },
  { name: "Alfàbrega", optional_description: "Herba fresca per tomàquet i pasta." },
  { name: "Julivert", optional_description: "Herba fresca per acabats i picades." },
  { name: "Llorer", optional_description: "Fulla aromàtica per guisats i brous." },
  { name: "Ametlles torrades", optional_description: "Fruit sec per picades i postres.", allergies: [ "Fruits secs" ] },
  { name: "Avellanes torrades", optional_description: "Fruit sec per picades i salses.", allergies: [ "Fruits secs" ] },
  { name: "Sèsam torrat", optional_description: "Llavor per amanides i hummus.", allergies: [ "Sèsam" ] },
  { name: "Llimona", optional_description: "Cítric per amanir i aromatitzar." },
  { name: "Poma", optional_description: "Fruita fresca per postres i amanides." },
  { name: "Plàtan", optional_description: "Fruita dolça per esmorzars i postres." },
  { name: "Sucre", optional_description: "Endolcidor per postres." },
  { name: "Mel", optional_description: "Endolcidor natural." },
  { name: "Xocolata negra", optional_description: "Per postres i berenars." },
  { name: "Llevat químic", optional_description: "Impulsor per bescuits i masses." },
  { name: "Brou de verdures", optional_description: "Base líquida per arrossos, sopes i cremes." },
  { name: "Aigua", optional_description: "Base líquida neutra." }
]

ingredient_images = {
  "Arròs bomba" => "ingredients/arros_bomba.jpg",
  "Macarrons" => "ingredients/macarrones.jpg",
  "Espaguetis" => "ingredients/spaghetti.jpg",
  "Farina de blat" => "ingredients/farina_blat.jpg",
  "Pa ratllat" => "ingredients/pa_ratllat.jpg",
  "Patata" => "ingredients/patata.jpg",
  "Ceba" => "ingredients/ceba.jpg",
  "Tomàquet madur" => "ingredients/tomaquet.jpg",
  "Tomàquet triturat" => "ingredients/tomaquet_triturat.jpg",
  "Pebrot vermell" => "ingredients/pebrot_vermell.jpg",
  "Pebrot verd" => "ingredients/pebrot_verd.jpg",
  "Pastanaga" => "ingredients/pastanaga.jpg",
  "Carbassó" => "ingredients/carbasso.jpg",
  "Albergínia" => "ingredients/alberginia.jpg",
  "Porro" => "ingredients/porro.jpg",
  "Api" => "ingredients/api.jpg",
  "Enciam" => "ingredients/enciam.jpg",
  "Ruca" => "ingredients/ruca.jpg",
  "Cigrons cuits" => "ingredients/cigrons.jpg",
  "Llenties cuites" => "ingredients/llenties.jpg",
  "Mongetes seques cuites" => "ingredients/mongetes.jpg",
  "Pèsols" => "ingredients/pesols.jpg",
  "Pollastre" => "ingredients/pollastre.jpg",
  "Vedella picada" => "ingredients/vedella_picada.jpg",
  "Bacallà dessalat" => "ingredients/bacalla.jpg",
  "Lluç" => "ingredients/lluc.jpg",
  "Gambes" => "ingredients/gambes.jpg",
  "Tonyina en conserva" => "ingredients/tonyina.jpg",
  "Ous" => "ingredients/ous.jpg",
  "Llet" => "ingredients/llet.jpg",
  "Mantega" => "ingredients/mantega.jpg",
  "Formatge ratllat" => "ingredients/formatge_rallat.jpg",
  "Iogurt natural" => "ingredients/yogur.jpg",
  "Nata líquida" => "ingredients/nata.jpg",
  "Oli d'oliva verge extra" => "ingredients/oli_oliva.jpg",
  "Vinagre de vi" => "ingredients/vinagre.jpg",
  "Sal" => "ingredients/sal.jpg",
  "Pebre negre" => "ingredients/pebre.jpg",
  "Pebre vermell dolç" => "ingredients/pebre_vermell.jpg",
  "Comí" => "ingredients/comi.jpg",
  "Cúrcuma" => "ingredients/curcuma.jpg",
  "Orenga" => "ingredients/orenga.jpg",
  "Alfàbrega" => "ingredients/alfabrega.jpg",
  "Julivert" => "ingredients/julivert.jpg",
  "Llorer" => "ingredients/llorer.jpg",
  "Ametlles torrades" => "ingredients/ametlles.jpg",
  "Avellanes torrades" => "ingredients/avellanes.jpg",
  "Sèsam torrat" => "ingredients/sesam.jpg",
  "Llimona" => "ingredients/llimona.jpg",
  "Poma" => "ingredients/poma.jpg",
  "Plàtan" => "ingredients/platan.jpg",
  "Sucre" => "ingredients/sucre.jpg",
  "Mel" => "ingredients/mel.jpg",
  "Xocolata negra" => "ingredients/xocolata_negra.jpg",
  "Llevat químic" => "ingredients/llevat.jpg",
  "Brou de verdures" => "ingredients/brou_verdures.jpg",
  "Aigua" => "ingredients/aigua.jpg"
}

ingredients.each do |data|
  ingredient = Ingredient.find_or_initialize_by(name: data[:name])
  ingredient.assign_attributes(optional_description: data[:optional_description])
  ingredient.save!
  ingredient.allergies = Allergy.where(name: data.fetch(:allergies, [])).to_a
  image = data[:image] || ingredient_images[data[:name]]
  attach_seed_image(ingredient, :image, image) if image.present?
end
